<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2019, 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<FindBugsFilter
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="https://github.com/spotbugs/filter/3.1.0"
        xsi:schemaLocation="https://github.com/spotbugs/filter/3.1.0
                        https://raw.githubusercontent.com/spotbugs/spotbugs/3.1.0/spotbugs/etc/findbugsfilter.xsd">
    <Match>
        <Class name="io.helidon.integrations.cdi.hibernate.CDISEJtaPlatformProvider"/>
        <!--
            Spotbugs seems to think that the JtaPlatformProvider#getProvidedJtaPlatform() method contract prohibits
            null. It thinks, specifically, that it is annotated with a "@Nonnull" [sic] annotation. It is not:
            https://github.com/hibernate/hibernate-orm/blob/6.1.7/hibernate-core/src/main/java/org/hibernate/engine/transaction/jta/platform/spi/JtaPlatformProvider.java#L20-L25
            This exclusion corrects this strange state of affairs.
        -->
        <Bug pattern="NP_NONNULL_RETURN_VIOLATION"/>
    </Match>
    <Match>
        <Class name="io.helidon.integrations.cdi.hibernate.DataSourceBackedDialectFactory"/>
        <!--
            In the following construct:

                try (Connection c = ds.getConnection()) {
                    dmd = c.getMetaData();
                } catch (SQLException e) {
                    throw BasicSQLExceptionConverter.INSTANCE.convert(e);
                }

            Spotbugs reports an unnecessary null check on the line containing "catch (SQLException e)". My guess is it
            is confused by the bytecodes emitted by the try-with-resources source construct. In any event, it is wrong.
        -->
        <Bug pattern="RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE"/>
    </Match>
</FindBugsFilter>
